export enum BoardType {
  ROOM_ONLY = 'ROOM_ONLY',
  BREAKFAST = 'BREAKFAST',
  HALF_BOARD = 'HALF_BOARD',
  FULL_BOARD = 'FULL_BOARD',
  ALL_INCLUSIVE = 'ALL_INCLUSIVE',
}

export enum Amenities {
  SWIMMING_POOL = 'SWIMMING_POOL',
  SPA = 'SPA',
  FITNESS_CENTER = 'FITNESS_CENTER',
  AIR_CONDITIONING = 'AIR_CONDITIONING',
  RESTAURANT = 'RESTAURANT',
  PARKING = 'PARKING',
  PETS_ALLOWED = 'PETS_ALLOWED',
  BUSINESS_CENTER = 'BUSINESS_CENTER',
  DISABLED_FACILITIES = 'DISABLED_FACILITIES',
  WIFI = 'WIFI',
  MEETING_ROOMS = 'MEETING_ROOMS',
  NO_KID_ALLOWED = 'NO_KID_ALLOWED',
}
